version: '3'

services:
  angular-app:
    build: .
    ports:
      - "40001:4200"
    volumes:
      - .:/myapp
      - node_modules_volume:/myapp/node_modules
    tty: true
volumes:
  node_modules_volume:
    name: angular_node_modules
